import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { getServerSession } from "next-auth";
import SessionProvider from "./lib/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "mychat-francostan",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
        <Providers>{children}</Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
